---
- name: "copy kubernetes.repo"
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/
    
- name: "copy docker.repo"
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/
 
- name: "This command will reset yum cache"
  shell:
    cmd: yum clean all && yum makecache
 
- name: "Install kube* application"
  yum:
    name: "{{ item }}"
    state: installed
    disablerepo: "*"
    enablerepo: "kubernetes,docker"
  loop:
    - 'kubectl-{{ k8s_version }}'
    - 'kubelet-{{ k8s_version }}'
    - 'kubeadm-{{ k8s_version }}'
    - 'docker-ce'
 
- name: "enable and start services"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - 'kubelet'
  - 'docker'


