# - hosts: hbase-master1
# - hosts: hbase-master2
# - hosts: hbase-slave01
# - hosts: hbase-slave02
- hosts: hbase-slave03
# - hosts: hbase-slave04
  gather_facts: no
  remote_user: root
  vars_files:
    - vars/var_oracle.yml
  # vars:
  #   oracle_path: "/data/oracle"
  roles:
    - base
    - oracle
